Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
... Bill = input('what is the total bill?\n')
... 
... percentage_of_tip = input('What percentage of tip would you like to give?10,12,15,20?\n')
... 
... number_of_people = input('How many people to split the bill?\n')
... 
... tip = (int(percentage_of_tip) / 100) * int(Bill)
... 
... total_bill = int(Bill) + tip
... 
... each_person_pay = total_bill / int(number_of_people)
... 
... print(f'Each person\'s bill is {each_person_pay}')   
... 
